ERROR:django.request:Internal Server Error: /document/forward/3
Traceback (most recent call last):
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/d/KonzaApps/apps/doc/views.py", line 73, in forward_file
    template = render_to_string('doc/email_template.html',
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 1372, in url
    viewname = parser.compile_filter(bits[1])
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ',' from ''view_shared','
ERROR:django.request:Internal Server Error: /document/forward/3
Traceback (most recent call last):
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/d/KonzaApps/apps/doc/views.py", line 73, in forward_file
    template = render_to_string('doc/email_template.html',
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/mnt/d/KonzaApps/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_shared' with keyword arguments '{'file_id': ''}' not found. 1 pattern(s) tried: ['dashboard/shared/(?P<file_id>[0-9]+)/$']
DEBUG:asyncio:Using selector: EpollSelector
